import { useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { useTheme } from "../contexts/ThemeContext";
import {
  FaSun,
  FaMoon,
  FaGithub,
  FaExternalLinkAlt,
  FaStar,
  FaCodeBranch,
} from "react-icons/fa";

export default function Portfolio() {
  const { username } = useParams();
  const { theme, toggleTheme, isDark } = useTheme();

  // TODO: Fetch portfolio data from Firestore based on username
  // For now, show a shell/placeholder layout

  return (
    <div
      className={`min-h-screen transition-colors duration-300 ${
        isDark ? "bg-surface-900 text-text-primary" : "bg-gray-50 text-gray-900"
      }`}
    >
      {/* Theme Toggle */}
      <button
        onClick={toggleTheme}
        className={`fixed right-6 top-6 z-50 rounded-full p-3 shadow-lg transition-colors ${
          isDark
            ? "bg-surface-700 text-yellow-400 hover:bg-surface-600"
            : "bg-white text-gray-700 hover:bg-gray-100"
        }`}
        title={`Switch to ${isDark ? "light" : "dark"} mode`}
      >
        {isDark ? <FaSun /> : <FaMoon />}
      </button>

      {/* Hero Section */}
      <section className="flex min-h-[60vh] flex-col items-center justify-center px-6 text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
        >
          {/* Letter Avatar */}
          <div
            className={`mx-auto mb-6 flex h-24 w-24 items-center justify-center rounded-full text-4xl font-bold ${
              isDark
                ? "bg-primary/20 text-primary"
                : "bg-indigo-100 text-indigo-600"
            }`}
          >
            {username?.charAt(0).toUpperCase() || "?"}
          </div>

          <h1 className="mb-2 text-4xl font-bold md:text-5xl">{username}</h1>
          <p
            className={`text-lg ${isDark ? "text-text-secondary" : "text-gray-600"}`}
          >
            {/* TODO: AI-generated bio will go here */}
            Developer portfolio generated by GitFolio
          </p>

          <div className="mt-6 flex items-center justify-center gap-4">
            <a
              href={`https://github.com/${username}`}
              target="_blank"
              rel="noopener noreferrer"
              className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors ${
                isDark
                  ? "bg-surface-700 text-text-primary hover:bg-surface-600"
                  : "bg-gray-200 text-gray-800 hover:bg-gray-300"
              }`}
            >
              <FaGithub />
              GitHub Profile
              <FaExternalLinkAlt className="text-xs" />
            </a>
          </div>
        </motion.div>
      </section>

      {/* Skills Section Placeholder */}
      <section className="px-6 py-16">
        <div className="mx-auto max-w-4xl">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-8 text-center text-2xl font-bold"
          >
            Skills
          </motion.h2>
          <div className="flex flex-wrap justify-center gap-3">
            {/* TODO: Populate from GitHub data + AI extraction */}
            {["JavaScript", "React", "Node.js", "Python", "TypeScript"].map(
              (skill) => (
                <span
                  key={skill}
                  className={`rounded-full px-4 py-2 text-sm font-medium ${
                    isDark
                      ? "bg-surface-700 text-text-secondary"
                      : "bg-gray-200 text-gray-700"
                  }`}
                >
                  {skill}
                </span>
              )
            )}
          </div>
        </div>
      </section>

      {/* Projects Section Placeholder */}
      <section className="px-6 py-16">
        <div className="mx-auto max-w-5xl">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-8 text-center text-2xl font-bold"
          >
            Projects
          </motion.h2>
          <div className="grid gap-6 md:grid-cols-2">
            {/* TODO: Populate from GitHub repos */}
            {[1, 2, 3, 4].map((i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className={`rounded-xl border p-6 ${
                  isDark
                    ? "border-surface-600 bg-surface-800"
                    : "border-gray-200 bg-white"
                }`}
              >
                <h3 className="mb-2 text-lg font-semibold">
                  Project {i}
                </h3>
                <p
                  className={`mb-4 text-sm ${isDark ? "text-text-secondary" : "text-gray-600"}`}
                >
                  Project description will be generated by AI from your
                  repository data.
                </p>
                <div className="flex items-center gap-4 text-sm">
                  <span className="flex items-center gap-1 text-text-muted">
                    <FaStar className="text-yellow-500" /> 0
                  </span>
                  <span className="flex items-center gap-1 text-text-muted">
                    <FaCodeBranch /> 0
                  </span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Stats Section Placeholder */}
      <section className="px-6 py-16">
        <div className="mx-auto max-w-3xl">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-8 text-center text-2xl font-bold"
          >
            GitHub Stats
          </motion.h2>
          <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
            {[
              { label: "Repositories", value: "--" },
              { label: "Stars", value: "--" },
              { label: "Followers", value: "--" },
              { label: "Following", value: "--" },
            ].map((stat) => (
              <div
                key={stat.label}
                className={`rounded-xl p-6 text-center ${
                  isDark ? "bg-surface-800" : "bg-white shadow-sm"
                }`}
              >
                <div className="text-3xl font-bold text-primary">
                  {stat.value}
                </div>
                <div
                  className={`mt-1 text-sm ${isDark ? "text-text-muted" : "text-gray-500"}`}
                >
                  {stat.label}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Section Placeholder */}
      <section className="px-6 py-16">
        <div className="mx-auto max-w-xl text-center">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-4 text-2xl font-bold"
          >
            Get in Touch
          </motion.h2>
          <p
            className={`mb-6 ${isDark ? "text-text-secondary" : "text-gray-600"}`}
          >
            {/* TODO: Populate from GitHub profile data */}
            Contact information will be pulled from your GitHub profile.
          </p>
        </div>
      </section>

      {/* Footer */}
      <footer
        className={`border-t px-6 py-8 text-center text-sm ${
          isDark
            ? "border-surface-700 text-text-muted"
            : "border-gray-200 text-gray-500"
        }`}
      >
        Built with{" "}
        <a
          href="/"
          className="font-medium text-primary transition-colors hover:text-primary-light"
        >
          GitFolio
        </a>
      </footer>
    </div>
  );
}
