import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { useTheme } from "../contexts/ThemeContext";
import {
  FaSun,
  FaMoon,
  FaGithub,
  FaExternalLinkAlt,
  FaStar,
  FaCodeBranch,
  FaMapMarkerAlt,
  FaEnvelope,
  FaLink,
  FaTwitter,
  FaBuilding,
  FaFire,
  FaCode,
} from "react-icons/fa";
import { getPortfolioByUsername } from "../services/firestore";
import { LANGUAGE_COLORS } from "../services/github";
import Loader from "../components/common/Loader";

export default function Portfolio() {
  const { username } = useParams();
  const { theme, toggleTheme, isDark } = useTheme();
  const [portfolio, setPortfolio] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    async function loadPortfolio() {
      try {
        setLoading(true);
        setError(false);
        const data = await getPortfolioByUsername(username);
        setPortfolio(data);
      } catch (err) {
        console.error("Error loading portfolio:", err);
        setError(true);
      } finally {
        setLoading(false);
      }
    }
    if (username) loadPortfolio();
  }, [username]);

  // Loading state
  if (loading) {
    return (
      <div
        className={`flex min-h-screen items-center justify-center ${
          isDark ? "bg-surface-900" : "bg-gray-50"
        }`}
      >
        <Loader />
      </div>
    );
  }

  // Not found state
  if (error || !portfolio) {
    return (
      <div
        className={`flex min-h-screen flex-col items-center justify-center px-6 ${
          isDark ? "bg-surface-900 text-text-primary" : "bg-gray-50 text-gray-900"
        }`}
      >
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center"
        >
          <div className="mx-auto mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-primary/10 text-4xl">
            ?
          </div>
          <h1 className="mb-2 text-2xl font-bold">Portfolio Not Found</h1>
          <p
            className={`mb-6 ${isDark ? "text-text-secondary" : "text-gray-600"}`}
          >
            No portfolio has been generated for &quot;{username}&quot; yet.
          </p>
          <Link
            to="/dashboard"
            className="inline-flex items-center gap-2 rounded-lg bg-primary px-6 py-3 font-semibold text-white transition-colors hover:bg-primary-dark"
          >
            Generate Portfolio
          </Link>
        </motion.div>
      </div>
    );
  }

  // Destructure portfolio data
  const {
    name,
    bio,
    avatarUrl,
    location,
    company,
    blog,
    email,
    twitterUsername,
    skills = [],
    projects = [],
    languages = [],
    contributions = {},
    stats = {},
    readmeSections,
  } = portfolio;

  // Determine if we have contact info
  const hasContact = location || email || blog || twitterUsername || company;

  return (
    <div
      className={`min-h-screen transition-colors duration-300 ${
        isDark ? "bg-surface-900 text-text-primary" : "bg-gray-50 text-gray-900"
      }`}
    >
      {/* Theme Toggle */}
      <button
        onClick={toggleTheme}
        className={`fixed right-6 top-6 z-50 rounded-full p-3 shadow-lg transition-colors ${
          isDark
            ? "bg-surface-700 text-yellow-400 hover:bg-surface-600"
            : "bg-white text-gray-700 hover:bg-gray-100"
        }`}
        title={`Switch to ${isDark ? "light" : "dark"} mode`}
      >
        {isDark ? <FaSun /> : <FaMoon />}
      </button>

      {/* Hero Section */}
      <section className="flex min-h-[60vh] flex-col items-center justify-center px-6 text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
        >
          {/* Avatar */}
          {avatarUrl ? (
            <img
              src={avatarUrl}
              alt={name}
              className="mx-auto mb-6 h-24 w-24 rounded-full object-cover ring-4 ring-primary/20"
            />
          ) : (
            <div
              className={`mx-auto mb-6 flex h-24 w-24 items-center justify-center rounded-full text-4xl font-bold ${
                isDark
                  ? "bg-primary/20 text-primary"
                  : "bg-indigo-100 text-indigo-600"
              }`}
            >
              {(name || username)?.charAt(0).toUpperCase() || "?"}
            </div>
          )}

          <h1 className="mb-2 text-4xl font-bold md:text-5xl">
            {name || username}
          </h1>
          <p
            className={`max-w-2xl text-lg ${isDark ? "text-text-secondary" : "text-gray-600"}`}
          >
            {bio || "Developer portfolio generated by GitFolio"}
          </p>

          <div className="mt-6 flex items-center justify-center gap-4">
            <a
              href={`https://github.com/${username}`}
              target="_blank"
              rel="noopener noreferrer"
              className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors ${
                isDark
                  ? "bg-surface-700 text-text-primary hover:bg-surface-600"
                  : "bg-gray-200 text-gray-800 hover:bg-gray-300"
              }`}
            >
              <FaGithub />
              GitHub Profile
              <FaExternalLinkAlt className="text-xs" />
            </a>
          </div>
        </motion.div>
      </section>

      {/* Skills Section */}
      {skills.length > 0 && (
        <section className="px-6 py-16">
          <div className="mx-auto max-w-4xl">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="mb-8 text-center text-2xl font-bold"
            >
              Skills
            </motion.h2>
            <div className="flex flex-wrap justify-center gap-3">
              {skills.map((skill) => (
                <motion.span
                  key={skill}
                  initial={{ opacity: 0, scale: 0.8 }}
                  whileInView={{ opacity: 1, scale: 1 }}
                  viewport={{ once: true }}
                  className={`rounded-full px-4 py-2 text-sm font-medium ${
                    isDark
                      ? "bg-surface-700 text-text-secondary"
                      : "bg-gray-200 text-gray-700"
                  }`}
                >
                  {skill}
                </motion.span>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Most Used Languages Section - GitHub Style */}
      {languages.length > 0 && (
        <section className="px-6 py-16">
          <div className="mx-auto max-w-4xl">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className={`rounded-xl border p-6 ${
                isDark
                  ? "border-surface-600 bg-surface-800"
                  : "border-gray-200 bg-white shadow-sm"
              }`}
            >
              <div className="mb-4 flex items-center gap-2">
                <FaCode className={isDark ? "text-text-secondary" : "text-gray-500"} />
                <h2 className="text-lg font-semibold">Languages</h2>
              </div>

              {/* GitHub-style horizontal stacked bar */}
              <div className="mb-4 flex h-4 w-full overflow-hidden rounded-full">
                {languages.slice(0, 8).map((lang) => (
                  <div
                    key={lang.language}
                    className="h-full transition-all hover:opacity-80"
                    style={{
                      width: `${lang.percentage}%`,
                      backgroundColor:
                        LANGUAGE_COLORS[lang.language] || LANGUAGE_COLORS.default,
                    }}
                    title={`${lang.language}: ${lang.percentage}%`}
                  />
                ))}
              </div>

              {/* Language legend in a flex wrap */}
              <div className="flex flex-wrap gap-x-4 gap-y-2">
                {languages.slice(0, 8).map((lang) => (
                  <div key={lang.language} className="flex items-center gap-2">
                    <span
                      className="h-3 w-3 rounded-full"
                      style={{
                        backgroundColor:
                          LANGUAGE_COLORS[lang.language] || LANGUAGE_COLORS.default,
                      }}
                    />
                    <span
                      className={`text-sm ${
                        isDark ? "text-text-primary" : "text-gray-800"
                      }`}
                    >
                      {lang.language}
                    </span>
                    <span
                      className={`text-xs ${
                        isDark ? "text-text-muted" : "text-gray-500"
                      }`}
                    >
                      {lang.percentage}%
                    </span>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </section>
      )}

      {/* Contribution Activity Section - GitHub Style Grid */}
      {(contributions.totalRecent > 0 || stats.currentStreak > 0) && (
        <section className="px-6 py-16">
          <div className="mx-auto max-w-4xl">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className={`rounded-xl border p-6 ${
                isDark
                  ? "border-surface-600 bg-surface-800"
                  : "border-gray-200 bg-white shadow-sm"
              }`}
            >
              <div className="mb-4 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FaFire className="text-orange-500" />
                  <h2 className="text-lg font-semibold">
                    {contributions.totalRecent || 0} contributions in the last month
                  </h2>
                </div>
                {stats.currentStreak > 0 && (
                  <div className="flex items-center gap-1 text-sm">
                    <FaFire className="text-orange-500" />
                    <span className="font-semibold text-orange-500">
                      {stats.currentStreak} day streak
                    </span>
                  </div>
                )}
              </div>

              {/* GitHub-style contribution grid */}
              {contributions.contributionsByDate && (
                <div className="overflow-x-auto">
                  <div className="inline-block">
                    {/* Month labels */}
                    <div
                      className={`mb-1 ml-8 flex text-xs ${
                        isDark ? "text-text-muted" : "text-gray-500"
                      }`}
                    >
                      {(() => {
                        const weeks = 5;
                        const months = [];
                        const today = new Date();
                        for (let w = 0; w < weeks; w++) {
                          const weekStart = new Date(today);
                          weekStart.setDate(weekStart.getDate() - (weeks - 1 - w) * 7);
                          const monthName = weekStart.toLocaleDateString("en", { month: "short" });
                          if (w === 0 || months[months.length - 1]?.month !== monthName) {
                            months.push({ month: monthName, week: w });
                          }
                        }
                        return months.map((m, i) => (
                          <span
                            key={i}
                            style={{ marginLeft: i === 0 ? `${m.week * 20}px` : `${(m.week - months[i-1]?.week - 1) * 20}px` }}
                            className="w-20"
                          >
                            {m.month}
                          </span>
                        ));
                      })()}
                    </div>

                    <div className="flex gap-1">
                      {/* Day labels */}
                      <div
                        className={`flex flex-col gap-1 text-xs ${
                          isDark ? "text-text-muted" : "text-gray-500"
                        }`}
                      >
                        <span className="h-3 leading-3">Mon</span>
                        <span className="h-3 leading-3">Wed</span>
                        <span className="h-3 leading-3">Fri</span>
                      </div>

                      {/* Contribution grid */}
                      <div className="flex gap-[3px]">
                        {Array.from({ length: 5 }).map((_, weekIndex) => (
                          <div key={weekIndex} className="flex flex-col gap-[3px]">
                            {Array.from({ length: 7 }).map((_, dayIndex) => {
                              const date = new Date();
                              const daysAgo = (4 - weekIndex) * 7 + (6 - dayIndex);
                              date.setDate(date.getDate() - daysAgo);
                              const dateStr = date.toISOString().split("T")[0];
                              const count = contributions.contributionsByDate[dateStr] || 0;

                              const getColor = () => {
                                if (count === 0) return isDark ? "bg-[#161b22]" : "bg-[#ebedf0]";
                                if (count < 3) return "bg-[#9be9a8]";
                                if (count < 6) return "bg-[#40c463]";
                                if (count < 10) return "bg-[#30a14e]";
                                return "bg-[#216e39]";
                              };

                              return (
                                <div
                                  key={dayIndex}
                                  className={`h-3 w-3 rounded-[2px] ${getColor()} cursor-pointer transition-transform hover:ring-1 hover:ring-white/50`}
                                  title={`${dateStr}: ${count} contribution${count !== 1 ? "s" : ""}`}
                                />
                              );
                            })}
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Legend */}
                    <div
                      className={`mt-3 flex items-center justify-end gap-2 text-xs ${
                        isDark ? "text-text-muted" : "text-gray-500"
                      }`}
                    >
                      <span>Less</span>
                      <div className="flex gap-1">
                        <div className={`h-3 w-3 rounded-[2px] ${isDark ? "bg-[#161b22]" : "bg-[#ebedf0]"}`} />
                        <div className="h-3 w-3 rounded-[2px] bg-[#9be9a8]" />
                        <div className="h-3 w-3 rounded-[2px] bg-[#40c463]" />
                        <div className="h-3 w-3 rounded-[2px] bg-[#30a14e]" />
                        <div className="h-3 w-3 rounded-[2px] bg-[#216e39]" />
                      </div>
                      <span>More</span>
                    </div>
                  </div>
                </div>
              )}
            </motion.div>
          </div>
        </section>
      )}

      {/* Projects Section */}
      {projects.length > 0 && (
        <section className="px-6 py-16">
          <div className="mx-auto max-w-5xl">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="mb-8 text-center text-2xl font-bold"
            >
              Projects
            </motion.h2>
            <div className="grid gap-6 md:grid-cols-2">
              {projects.map((project, index) => (
                <motion.div
                  key={project.name}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: index * 0.1 }}
                  className={`group rounded-xl border p-6 transition-colors ${
                    isDark
                      ? "border-surface-600 bg-surface-800 hover:border-surface-500"
                      : "border-gray-200 bg-white hover:border-gray-300"
                  }`}
                >
                  <div className="mb-2 flex items-start justify-between">
                    <h3 className="text-lg font-semibold">{project.name}</h3>
                    <div className="flex items-center gap-2">
                      {project.homepage && (
                        <a
                          href={project.homepage}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-text-muted transition-colors hover:text-primary"
                          title="Live demo"
                        >
                          <FaExternalLinkAlt className="text-xs" />
                        </a>
                      )}
                      {project.url && (
                        <a
                          href={project.url}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-text-muted transition-colors hover:text-primary"
                          title="Source code"
                        >
                          <FaGithub />
                        </a>
                      )}
                    </div>
                  </div>
                  <p
                    className={`mb-4 text-sm ${isDark ? "text-text-secondary" : "text-gray-600"}`}
                  >
                    {project.description || "A GitHub repository."}
                  </p>
                  <div className="flex items-center gap-4 text-sm">
                    {project.language && (
                      <span
                        className={`flex items-center gap-1 ${isDark ? "text-text-muted" : "text-gray-500"}`}
                      >
                        <span className="inline-block h-3 w-3 rounded-full bg-primary" />
                        {project.language}
                      </span>
                    )}
                    <span
                      className={`flex items-center gap-1 ${isDark ? "text-text-muted" : "text-gray-500"}`}
                    >
                      <FaStar className="text-yellow-500" /> {project.stars}
                    </span>
                    <span
                      className={`flex items-center gap-1 ${isDark ? "text-text-muted" : "text-gray-500"}`}
                    >
                      <FaCodeBranch /> {project.forks}
                    </span>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* Stats Section */}
      <section className="px-6 py-16">
        <div className="mx-auto max-w-3xl">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-8 text-center text-2xl font-bold"
          >
            GitHub Stats
          </motion.h2>
          <div className="grid grid-cols-2 gap-6 md:grid-cols-4">
            {[
              { label: "Repositories", value: stats.repos ?? "--" },
              { label: "Stars", value: stats.stars ?? "--" },
              { label: "Followers", value: stats.followers ?? "--" },
              { label: "Following", value: stats.following ?? "--" },
            ].map((stat, index) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className={`rounded-xl p-6 text-center ${
                  isDark ? "bg-surface-800" : "bg-white shadow-sm"
                }`}
              >
                <div className="text-3xl font-bold text-primary">
                  {stat.value}
                </div>
                <div
                  className={`mt-1 text-sm ${isDark ? "text-text-muted" : "text-gray-500"}`}
                >
                  {stat.label}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* README Sections (Education, Experience, Achievements, etc.) */}
      {readmeSections && Object.keys(readmeSections).length > 0 && (
        <section className="px-6 py-16">
          <div className="mx-auto max-w-4xl">
            {Object.entries(readmeSections).map(([sectionKey, items]) => {
              if (!Array.isArray(items) || items.length === 0) return null;
              const sectionTitle =
                sectionKey.charAt(0).toUpperCase() + sectionKey.slice(1);
              return (
                <div key={sectionKey} className="mb-12 last:mb-0">
                  <motion.h2
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="mb-6 text-center text-2xl font-bold"
                  >
                    {sectionTitle}
                  </motion.h2>
                  <div className="space-y-3">
                    {items.map((item, idx) => (
                      <motion.div
                        key={idx}
                        initial={{ opacity: 0, x: -10 }}
                        whileInView={{ opacity: 1, x: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: idx * 0.05 }}
                        className={`rounded-lg px-5 py-4 ${
                          isDark
                            ? "bg-surface-800"
                            : "bg-white shadow-sm"
                        }`}
                      >
                        <p className={isDark ? "text-text-secondary" : "text-gray-700"}>
                          {typeof item === "string" ? item : JSON.stringify(item)}
                        </p>
                      </motion.div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </section>
      )}

      {/* Contact Section */}
      {hasContact && (
        <section className="px-6 py-16">
          <div className="mx-auto max-w-xl text-center">
            <motion.h2
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="mb-6 text-2xl font-bold"
            >
              Get in Touch
            </motion.h2>
            <div className="flex flex-wrap justify-center gap-4">
              {location && (
                <span
                  className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm ${
                    isDark
                      ? "bg-surface-700 text-text-secondary"
                      : "bg-gray-100 text-gray-700"
                  }`}
                >
                  <FaMapMarkerAlt className="text-primary" />
                  {location}
                </span>
              )}
              {company && (
                <span
                  className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm ${
                    isDark
                      ? "bg-surface-700 text-text-secondary"
                      : "bg-gray-100 text-gray-700"
                  }`}
                >
                  <FaBuilding className="text-primary" />
                  {company}
                </span>
              )}
              {email && (
                <a
                  href={`mailto:${email}`}
                  className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm transition-colors ${
                    isDark
                      ? "bg-surface-700 text-text-secondary hover:bg-surface-600"
                      : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                  }`}
                >
                  <FaEnvelope className="text-primary" />
                  {email}
                </a>
              )}
              {blog && (
                <a
                  href={blog.startsWith("http") ? blog : `https://${blog}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm transition-colors ${
                    isDark
                      ? "bg-surface-700 text-text-secondary hover:bg-surface-600"
                      : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                  }`}
                >
                  <FaLink className="text-primary" />
                  {blog.replace(/^https?:\/\//, "")}
                </a>
              )}
              {twitterUsername && (
                <a
                  href={`https://twitter.com/${twitterUsername}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm transition-colors ${
                    isDark
                      ? "bg-surface-700 text-text-secondary hover:bg-surface-600"
                      : "bg-gray-100 text-gray-700 hover:bg-gray-200"
                  }`}
                >
                  <FaTwitter className="text-primary" />
                  @{twitterUsername}
                </a>
              )}
            </div>
          </div>
        </section>
      )}

      {/* Footer */}
      <footer
        className={`border-t px-6 py-8 text-center text-sm ${
          isDark
            ? "border-surface-700 text-text-muted"
            : "border-gray-200 text-gray-500"
        }`}
      >
        Built with{" "}
        <a
          href="/"
          className="font-medium text-primary transition-colors hover:text-primary-light"
        >
          GitFolio
        </a>
      </footer>
    </div>
  );
}
