import { motion } from "framer-motion";
import { FaDownload, FaBold, FaItalic, FaLink } from "react-icons/fa";
import Navbar from "../components/common/Navbar";
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";

export default function Resume() {
  return (
    <div className="min-h-screen bg-background text-foreground transition-colors duration-300">
      <Navbar />

      <main className="px-6 pt-24 pb-16">
        <div className="mx-auto max-w-6xl">
          {/* Toolbar */}
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-border bg-card/50 p-4 backdrop-blur-md"
          >
            <div className="flex items-center gap-2">
              <h1 className="text-lg font-bold">
                Resume Editor
              </h1>
            </div>

            <div className="flex items-center gap-2">
              {/* Text formatting controls */}
              <Button variant="ghost" size="icon" title="Bold">
                <FaBold />
              </Button>
              <Button variant="ghost" size="icon" title="Italic">
                <FaItalic />
              </Button>
              <Button variant="ghost" size="icon" title="Add Link">
                <FaLink />
              </Button>

              <div className="mx-2 h-6 w-px bg-border" />

              {/* Download PDF */}
              <Button className="ml-2 gap-2" variant="default">
                <FaDownload />
                Download PDF
              </Button>
            </div>
          </motion.div>

          {/* Resume Paper -- always white */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="mx-auto max-w-[816px] rounded-lg bg-white p-12 shadow-2xl relative overflow-hidden ring-1 ring-border"
            style={{
              minHeight: "1056px", // Standard letter paper ratio
            }}
          >
            {/* Resume Content - always white background, dark text */}
            <div className="text-gray-900 font-sans print:p-0">
              {/* Header */}
              <div className="mb-6 border-b-2 border-gray-800 pb-4 text-center">
                <h2 className="text-3xl font-bold">
                  {/* TODO: Populate with user name */}
                  Your Name
                </h2>
                <p className="mt-1 text-sm text-gray-600">
                  {/* TODO: Populate with contact info */}
                  email@example.com | github.com/username | Location
                </p>
              </div>

              {/* Summary */}
              <div className="mb-6">
                <h3 className="mb-2 text-lg font-bold text-gray-800">
                  Summary
                </h3>
                <p className="text-sm leading-relaxed text-gray-700">
                  {/* TODO: AI-generated summary */}
                  Your professional summary will be generated from your GitHub
                  profile and projects using AI.
                </p>
              </div>

              {/* Skills */}
              <div className="mb-6">
                <h3 className="mb-2 text-lg font-bold text-gray-800">
                  Technical Skills
                </h3>
                <p className="text-sm text-gray-700">
                  {/* TODO: Populate from extracted skills */}
                  Skills will be auto-populated from your GitHub repositories.
                </p>
              </div>

              {/* Projects */}
              <div className="mb-6">
                <h3 className="mb-2 text-lg font-bold text-gray-800">
                  Projects
                </h3>
                {/* TODO: Populate from GitHub repos */}
                <div className="space-y-3">
                  <div>
                    <h4 className="text-sm font-semibold">Project Name</h4>
                    <p className="text-sm text-gray-600">
                      Project description generated by AI.
                    </p>
                  </div>
                </div>
              </div>

              {/* Education placeholder */}
              <div className="mb-6">
                <h3 className="mb-2 text-lg font-bold text-gray-800">
                  Education
                </h3>
                <p className="text-sm text-gray-600">
                  Add your education details to populate this section.
                </p>
              </div>
            </div>
          </motion.div>
        </div>
      </main>
    </div>
  );
}
